# สคริปต์สร้าง Secret ID ใหม่สำหรับสมาชิกในทีม

param(
    [Parameter(Mandatory=$true)]
    [string]$MemberName
)

Write-Host "=== Creating new Secret ID for: $MemberName ===" -ForegroundColor Cyan

# สร้าง Secret ID ใหม่
$SECRET_ID = docker exec -e VAULT_ADDR='http://127.0.0.1:8200' -e VAULT_TOKEN='dev-root-token-123' vault-server vault write -field=secret_id -f auth/approle/role/backend-dev/secret-id

if ($LASTEXITCODE -ne 0) {
    Write-Host "Error: Failed to create Secret ID" -ForegroundColor Red
    exit 1
}

# ดึง Role ID (ใช้ร่วมกันทั้งทีม)
$ROLE_ID = docker exec -e VAULT_ADDR='http://127.0.0.1:8200' -e VAULT_TOKEN='dev-root-token-123' vault-server vault read -field=role_id auth/approle/role/backend-dev/role-id

# สร้างโฟลเดอร์สำหรับสมาชิกคนนี้
$outputDir = "vault-credentials\$MemberName"
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

# บันทึกไฟล์ (UTF-8 without BOM)
[System.IO.File]::WriteAllText("$PWD\$outputDir\role-id", $ROLE_ID, (New-Object System.Text.UTF8Encoding $false))
[System.IO.File]::WriteAllText("$PWD\$outputDir\secret-id", $SECRET_ID, (New-Object System.Text.UTF8Encoding $false))

# สร้างไฟล์ README
@"
# Vault Credentials for $MemberName

Created: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Files:
- role-id: Common Role ID (shared with team)
- secret-id: Your unique Secret ID

## Next Steps:
1. Copy both files to: backend/vault-agent-config/
2. Follow TEAM_SETUP_GUIDE.md
3. Run: docker-compose -f docker-compose.agent.yml up -d

## Security:
- Keep these files private
- Do NOT commit to Git
- Delete from shared folders after copying

---
Auto-generated by create-member-credentials.ps1
"@ | Out-File -FilePath "$outputDir\README.txt" -Encoding utf8

Write-Host ""
Write-Host "=== Success! ===" -ForegroundColor Green
Write-Host ""
Write-Host "Credentials saved to: $outputDir" -ForegroundColor Cyan
Write-Host "Role ID: $ROLE_ID" -ForegroundColor Yellow
Write-Host "Secret ID: $SECRET_ID" -ForegroundColor Yellow
Write-Host ""
Write-Host "Send the '$outputDir' folder to $MemberName" -ForegroundColor Green
