// src/constants/AuditActions.js

export const AUDIT_ACTIONS = {
  // ==================== AUTHENTICATION ====================
  AUTH: {
    REGISTER: "USER_REGISTER",
    LOGIN: "USER_LOGIN",
    LOGOUT: "USER_LOGOUT",
    LOGOUT_ALL: "LOGOUT_ALL",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    VERIFY_RESET_TOKEN: "VERIFY_RESET_TOKEN",
    RESET_PASSWORD: "RESET_PASSWORD",
    GOOGLE_OAUTH_START: "GOOGLE_OAUTH_START",
    GOOGLE_OAUTH_CALLBACK: "GOOGLE_OAUTH_CALLBACK",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    REFRESH_TOKEN_ALT: "REFRESH_TOKEN_ALT",
    GET_PROFILE: "GET_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    CHANGE_EMAIL: "CHANGE_EMAIL",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
  },

  // ==================== COMPANY MANAGEMENT ====================
  COMPANY: {
    CREATE: "CREATE_COMPANY",
    VIEW_MY_COMPANIES: "VIEW_MY_COMPANIES",
    VIEW_DETAIL: "VIEW_COMPANY_DETAIL",
    UPDATE: "UPDATE_COMPANY",
    DELETE: "DELETE_COMPANY",
  },

  // ==================== MEMBER MANAGEMENT ====================
  MEMBER: {
    VIEW_ALL: "VIEW_MEMBERS",
    INVITE: "INVITE_MEMBER",
    CHANGE_ROLE: "CHANGE_MEMBER_ROLE",
    REMOVE: "REMOVE_MEMBER",
    TRANSFER_OWNERSHIP: "TRANSFER_OWNERSHIP",
  },

  // ==================== INVITATIONS ====================
  INVITATION: {
    SEND: "SEND_INVITATION",
    RESEND: "RESEND_INVITATION",
    ACCEPT: "ACCEPT_INVITATION",
    CANCEL: "CANCEL_INVITATION",
  },

  // ==================== OTP VERIFICATION ====================
  OTP: {
    SEND: "SEND_OTP",
    VERIFY: "VERIFY_OTP",
    RESEND: "RESEND_OTP",
    VERIFY_FAILED: "VERIFY_OTP_FAILED",
  },

  // ==================== AUDIT LOG ACCESS (ADMIN) ====================
  AUDIT_ACCESS: {
    VIEW_MY_ACTIVITY: "VIEW_MY_ACTIVITY",
    VIEW_ALL: "VIEW_ALL_LOGS",
    VIEW_RECENT: "VIEW_RECENT_LOGS",
    VIEW_SECURITY: "VIEW_SECURITY_LOGS",
    VIEW_FAILED: "VIEW_FAILED_LOGS",
    VIEW_SUSPICIOUS: "VIEW_SUSPICIOUS_LOGS",
    VIEW_STATS: "VIEW_LOG_STATS",
    EXPORT: "EXPORT_LOGS",
    VIEW_USER_LOGS: "VIEW_USER_LOGS",
    VIEW_CORRELATED: "VIEW_CORRELATED_LOGS",
    CLEANUP: "CLEANUP_LOGS",
  },

  // ==================== SYSTEM & SECURITY ====================
  SYSTEM: {
    STARTUP: "SYSTEM_STARTUP",
    SHUTDOWN: "SYSTEM_SHUTDOWN",
    BACKUP: "DATABASE_BACKUP",
    SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
    FAILED_LOGIN: "FAILED_LOGIN",
    OTHER: "OTHER",
  },
};
